<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnalyticsService.Application\AnalyticsService.Application.csproj" />
    <ProjectReference Include="..\AnalyticsService.Domain\AnalyticsService.Domain.csproj" />
  </ItemGroup>

</Project>
